## Aufgabe 4 (Typ C)
Definieren Sie eine Funktion zur Mittelwertberechnung von systolischen Blutdruckwerten und rufen
Sie diese Funktion mehrmals von außerhalb der Funktion auf. Beim Aufruf können der/die
Blutdruckwerte direkt durch Sie als Programmierer als aktuelle Parameter angegeben werden, eine
Abfrage der Werte vom Benutzer ist nicht notwendig. Am Bildschirm soll der jeweilige Mittelwert
erscheinen.
Es sollen mehrere Versionen dieses Programms mit folgenden Zusatzangaben erstellt werden:    

a) Es muss mindestens ein erster Blutdruckwert pflichtmäßig beim Funktionsaufruf übergeben
werden. Weitere Blutdruckwerte können in beliebiger Anzahl folgen. Die Funktion soll dann
zumindest mit zwei, mit einem und mit keinem Blutdruckwert/en aufgerufen werden. (Beim
letzten Aufruf müsste eine Fehlermeldung resultieren.)

In [2]:
def mw(bld,*b):  # bld ist ein Pflichtparamtert, *b ist ein flexibles Argument (und auch optional, für b muss kein Wert uebergeben werden)
                #es koennen beliebig viele Argumente fuer b uebergeben werden.
    summe = bld 
    Anzahl = 1
    for Zahl in b: 
        summe=summe+Zahl
        Anzahl=Anzahl+1
    Mittelwert = summe/Anzahl
    return Mittelwert

print(mw(120,100)) #Funktionsaufruf mit zwei aktuellen Parametern
print(mw(140)) #Funktionsaufruf mit nur einem Parameter für den pflicht Parameter bld
print(mw())# fuehrt zu einem Fehler, da ein Parameter uebergeben werden muss fuer bld

110.0
140.0


TypeError: mw() missing 1 required positional argument: 'bld'

b) Im Gegensatz zu a) soll auch der erste Blutdruckwert nicht pflichtmäßig beim Funktionsaufruf
übergeben werden müssen. Ruft man die Funktion ohne aktuellen Parameter (also ohne
Blutdruckwert) auf, soll der erste Blutdruckwert in der Funktion den Standardwert 120 erhalten
und somit der Mittelwert 120 ausgegeben werden (und keine Fehlermeldung)

In [1]:
def mw(bld=120,*b): #bld bekommt einen Standardwert zugewiesen, damit ist er zu einem optionalen Parameter geworden
    summe = bld
    Anzahl=1
    for Zahl in b:
        summe=summe+Zahl
        Anzahl=Anzahl+1
    Mittelwert = summe/Anzahl 
    return Mittelwert
print(mw())#wenn kein anderer Wert uebergeben wird, wird der Standardwert 120 verwendet

120.0


c) Im Gegensatz zu b) sollen nun drei Rückgabewerte von der Funktion zurückgegeben werden:    
• Die Anzahl der Blutdruckwerte, für die die Funktion aufgerufen wurde,    
• die Summe der Blutdruckwerte    
• sowie der Mittelwert der Blutdruckwerte    
Die drei Rückgabewerte sollen nach dem Funktionsaufruf in drei Variablen gespeichert werden 
und in einem Antwortsatz ausgegeben werden. Für die Übergabe z.B. der beiden Blutdruck-
werte 120 und 140 sollte am Bildschirm beim Ausführen Ihres Programms Folgendes
erscheinen: Anzahl RR-Werte: 2 / Summe: 260 / MW: 130.0

In [3]:
def mw(bld=120,*b):
    summe = bld 
    Anzahl=1
    for Zahl in b:
        summe=summe+Zahl
        Anzahl=Anzahl+1
    Mittelwert=summe/Anzahl
    return Anzahl,summe,Mittelwert #mehrere Rueckgabewerte. Tupel als Rueckgabewert
x,y,z=mw(120,140) #die Tupel werden den Variablen zugewiesen. X steht fuer Anzahl, y steht fuer Summe, z fuer Mittelwert
                    #dem Funktionsaufruf werden zwei aktuelle Parameter uebergeben
print("Anzahl RR-Werte:",x, "/","Summe:",y,"/", "MW",z) #Dem String werden die Variablen mit Komma getrennt angehaengt

Anzahl RR-Werte: 2 / Summe: 260 / MW 130.0
